@BaseApiUrl = http://localhost:7001/api


### Get all
GET {{BaseApiUrl}}/profiles


### Bla bla
PUT {{BaseApiUrl}}/profiles/684e1dae6a71463ddd0e4784
Content-Type: application/json
{
  "firstname": "Zane",
  "lastname":  "Doe",
  "title":     "Software Engineer",
  "avatarurl": "https://example.com/avatars/johndoe.png",
  "location":  "Gothenburg",
  "expertise": [
    { "name": "good boy", "icon": "🚲" },
    { "name": "Yes you are",   "icon": "☕" }
  ],
  "previoushelps": [
    {
      "withusername": "Alice",
      "topic":        "bike tuning",
      "dateutc":      "2025-06-14T10:30:00Z"
    },
    {
      "withusername": "delo",
      "topic":        "bike grinding",
      "dateutc":      "2025-06-14T10:30:00Z"
    }
  ]
}


### create account

POST {{BaseApiUrl}}/register
Content-Type: application/json

{
  "username": "test3",
  "password": "12345"
}
### login 
POST {{BaseApiUrl}}/login
Content-Type: application/json

{
  "username": "delo",
  "password": "12345"
}

### get by username
GET {{BaseApiUrl}}/username/delo

### bla
GET {{BaseApiUrl}}/profiles/delo




