@BaseApiUrl = http://localhost:7001/api


### Get all
GET {{BaseApiUrl}}/profiles


### Bla bla
PUT {{BaseApiUrl}}/profiles/684e153b63596858a7163694
Content-Type: application/json

{
  "firstname": "Zane",
  "lastname": "Doe",
  "title": "Fullstack Developer",
  "avatarurl": "https://example.com/avatar.jpg",
  "location": "Gothenburg"
}
### create account

POST {{BaseApiUrl}}/register
Content-Type: application/json

{
  "username": "test3",
  "password": "12345"
}
### login 
POST {{BaseApiUrl}}/login
Content-Type: application/json

{
  "username": "test3",
  "password": "12345"
}

### get by username
GET {{BaseApiUrl}}/username/test

### bla
GET {{BaseApiUrl}}/profiles/test2




